ALTER TABLE "hueat_menu_category"
ADD COLUMN "inside" BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN "outside" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "hueat_menu_item"
ADD COLUMN "inside" BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN "outside" BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE "hueat_menu_option"
ADD COLUMN "inside" BOOLEAN NOT NULL DEFAULT TRUE,
ADD COLUMN "outside" BOOLEAN NOT NULL DEFAULT TRUE;